server:
  port: 8080
  servlet:
    context-path: /sell
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wangsc?characterEncoding=UTF8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#logging:
#  pattern:
#    console: "%d - %msg%n"
#    file: /var/log/tomcat/sell.log
#    level: debug
#  path: /var/log/tomcat